In [1]:
import numpy as np

print(np.__version__)

2.4.0


In [2]:
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)

# 2D array
arr2 = np.array([[1,2,3],
                 [4,5,6]])

print(arr2)

# 3D array
arr3 = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr3)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
a = np.array([[1,2,3],[4,5,6]])

print("Shape:", a.shape)
print("Dimensions:", a.ndim)
print("Size:", a.size)
print("Data type:", a.dtype)
print("Item size:", a.itemsize)
print("Total bytes:", a.nbytes)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
Item size: 8
Total bytes: 48


In [4]:
# zeros
print(np.zeros((3,3)))

# ones
print(np.ones((2,4)))

# identity matrix
print(np.eye(4))

# full
print(np.full((3,3),7))

# random array
print(np.random.rand(3,3))

# random integers
print(np.random.randint(1,100,(4,4)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.08626497 0.94952408 0.11245054]
 [0.6523957  0.23467157 0.33684127]
 [0.94335603 0.75942372 0.97618233]]
[[16 85 75 75]
 [49 36  5 16]
 [63 44 48 68]
 [72 41 63 84]]


In [5]:
# arange
print(np.arange(0,10))

# step
print(np.arange(0,20,2))

# linspace
print(np.linspace(0,1,5))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]


In [6]:
a = np.arange(12)

print(a.reshape(3,4))

print(a.reshape(2,6))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [7]:
a = np.array([[1,2,3],[4,5,6]])

print(a.flatten())

print(a.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [8]:
a = np.array([10,20,30,40,50])

print(a[0])
print(a[3])
print(a[-1])

10
40
50


In [9]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0,0])
print(a[1,2])
print(a[2,1])

1
6
8


In [10]:
a = np.array([10,20,30,40,50,60])

print(a[1:4])
print(a[:3])
print(a[3:])
print(a[::2])

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]


In [11]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [12]:
a = np.array([1,2,3,4])

b = a.view()
c = a.copy()

a[0] = 99

print("Original:",a)
print("View:",b)
print("Copy:",c)

Original: [99  2  3  4]
View: [99  2  3  4]
Copy: [1 2 3 4]


In [13]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [14]:
a = np.array([1,2,3])

print(a + 10)
print(a * 5)
print(a ** 2)

[11 12 13]
[ 5 10 15]
[1 4 9]


In [15]:
a = np.array([1,4,9,16])

print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))
print(np.exp(a))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [16]:
a = np.array([10,20,30,40,50])

print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a))

30.0
30.0
14.142135623730951
200.0
10
50
150


In [17]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

print("Sum columns:",np.sum(a,axis=0))
print("Sum rows:",np.sum(a,axis=1))

Sum columns: [5 7 9]
Sum rows: [ 6 15]


In [18]:
a = np.array([10,20,30,40,50])

mask = a > 25

print(mask)
print(a[mask])

[False False  True  True  True]
[30 40 50]


In [19]:
a = np.array([5,10,15,20,25])

print(a[a>10])

[15 20 25]


In [20]:
a = np.array([30,10,50,20])

print(np.sort(a))

[10 20 30 50]


In [21]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])

print(np.dot(A,B))

[[19 22]
 [43 50]]


In [22]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [23]:
A = np.array([
    [1,2],
    [3,4]
])

print("Determinant:",np.linalg.det(A))

print("Inverse:",np.linalg.inv(A))

print("Eigenvalues:",np.linalg.eig(A))

Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [25]:
a = np.array([1,2,3,4,5,6])

print(np.split(a,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [26]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [27]:
print(np.random.rand(3,3))

print(np.random.randn(3,3))

print(np.random.randint(0,10,(3,3)))

np.random.seed(42)
print(np.random.rand(3))

[[0.431942   0.80775622 0.20897414]
 [0.33694106 0.12531553 0.29274968]
 [0.7082026  0.01041843 0.17444026]]
[[ 0.29664289  0.1958801  -1.24171245]
 [ 1.9227518   0.47725864  0.38934187]
 [-1.62733915  2.42259802 -1.05322151]]
[[6 5 6]
 [0 2 9]
 [9 1 4]]
[0.37454012 0.95071431 0.73199394]


In [28]:
data = np.array([
    [25,180],
    [30,175],
    [35,160],
    [40,170],
    [28,165]
])

ages = data[:,0]
heights = data[:,1]

print("Average age:",np.mean(ages))
print("Average height:",np.mean(heights))
print("Tallest:",np.max(heights))

Average age: 31.6
Average height: 170.0
Tallest: 180
