In [1]:
import numpy as np

In [2]:
students = np.array([
    [85, 78, 92],
    [70, 65, 80],
    [90, 88, 95],
    [60, 70, 75],
    [95, 92, 98]
])

print("Student Marks:\n", students)

Student Marks:
 [[85 78 92]
 [70 65 80]
 [90 88 95]
 [60 70 75]
 [95 92 98]]


In [3]:
# Average marks per student
avg_per_student = np.mean(students, axis=1)

# Average marks per subject
avg_per_subject = np.mean(students, axis=0)

print("Average per student:", avg_per_student)
print("Average per subject:", avg_per_subject)

Average per student: [85.         71.66666667 91.         68.33333333 95.        ]
Average per subject: [80.  78.6 88. ]


In [4]:
topper_index = np.argmax(avg_per_student)
topper_marks = students[topper_index]

print("Topper Index:", topper_index)
print("Topper Marks:", topper_marks)

Topper Index: 4
Topper Marks: [95 92 98]


In [5]:
def get_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 75:
        return "B"
    elif avg >= 60:
        return "C"
    else:
        return "Fail"

grades = np.array([get_grade(avg) for avg in avg_per_student])

print("Grades:", grades)

Grades: ['B' 'C' 'A' 'C' 'A']


In [6]:
# Students scoring above 80 average
high_performers = students[avg_per_student > 80]

print("High Performers:\n", high_performers)

High Performers:
 [[85 78 92]
 [90 88 95]
 [95 92 98]]


In [7]:
max_per_subject = np.max(students, axis=0)

print("Highest in each subject:", max_per_subject)

Highest in each subject: [95 92 98]


In [8]:
# Normalize between 0 and 1
normalized = students / 100

print("Normalized Data:\n", normalized)

Normalized Data:
 [[0.85 0.78 0.92]
 [0.7  0.65 0.8 ]
 [0.9  0.88 0.95]
 [0.6  0.7  0.75]
 [0.95 0.92 0.98]]


In [9]:
# Normalize between 0 and 1
normalized = students / 100

print("Normalized Data:\n", normalized)

Normalized Data:
 [[0.85 0.78 0.92]
 [0.7  0.65 0.8 ]
 [0.9  0.88 0.95]
 [0.6  0.7  0.75]
 [0.95 0.92 0.98]]


In [10]:
# Sort students by average marks
sorted_indices = np.argsort(avg_per_student)[::-1]

print("Ranking (best to worst):", sorted_indices)

Ranking (best to worst): [4 2 0 1 3]


In [11]:
bonus = np.array([5, 5, 5])

updated_scores = students + bonus

print("Updated Scores:\n", updated_scores)

Updated Scores:
 [[ 90  83  97]
 [ 75  70  85]
 [ 95  93 100]
 [ 65  75  80]
 [100  97 103]]


In [12]:
print("\n===== FINAL REPORT =====")
for i in range(len(students)):
    print(f"Student {i+1}: Avg={avg_per_student[i]:.2f}, Grade={grades[i]}")


===== FINAL REPORT =====
Student 1: Avg=85.00, Grade=B
Student 2: Avg=71.67, Grade=C
Student 3: Avg=91.00, Grade=A
Student 4: Avg=68.33, Grade=C
Student 5: Avg=95.00, Grade=A
